main: Challenges
name: KChallenges
version: ${project.version}
api-version: 1.16
commands:
  startgame:
    description: starts the challenge
  stopgame:
    description: stops the challenge
  challenges:
    description: challengemenu
